### ISSUE TITLE
Many thx for your nice work

### ISSUE THREAD

**Issue by alexinea** [yaosansi/aliyun-openapi-sdk-lite#2]
非常感谢你的方案，我将会把你的代码集成在 [Cosmos.Business.Extensions.SMS](https://github.com/OpenCosmosLoops/SMS) 中，作为该项目 Aliyun SMS 的发送客户端使用。

由于您的项目没有标明授权方式，而 [Cosmos.Business.Extensions.SMS](https://github.com/OpenCosmosLoops/SMS) 采用 MIT 许可，所以同时请求授权我使用你的代码。

Thx a lot :)

**Comment by yaosansi** [comment]
你好，非常荣幸使用本项目，本项目使用 Apache License 2.0 ，原来只在README.md体现了，现在已经重新声明了。

**Comment by alexinea** [comment]
已在相关文件内添加了 Apache License 2.0 声明：）
